"""initial tables

Revision ID: ce0603277109
Revises: 
Create Date: 2026-06-22 22:15:09.365562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0603277109'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('vendor_name', sa.String(length=512), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.Column('bill_to', sa.Text(), nullable=True),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('payment_terms', sa.String(length=256), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_file_hash'), 'invoices', ['file_hash'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_total_amount'), 'invoices', ['total_amount'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_name'), 'invoices', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_vendor_name'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_total_amount'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_file_hash'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
